server:
  port: 8888
  servlet:
    context-path: /api

spring:
  application:
    name: ai-code-gen
  profiles:
    active: local
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_gen
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.deepseek.api-key}
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
      max-token: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.deepseek.api-key}
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
      max-token: 8192

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: cn.pirate.aicodegen.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
